### ISSUE TITLE
auto keybinding for switch window

### ISSUE THREAD

**Issue by tumashu** [flexibeast/ewmctrl#8] opened 2015-05-06 22:26 UTC
what about add random a-z key to every window, so i can switch window by type a char?

**Comment by flexibeast** [comment] 2015-05-07 06:00
Good idea! i'll try to implement that as soon as i can. Thanks!

**Comment by flexibeast** [comment] 2015-05-09 15:40
This functionality is now available; as the README.md says:

```
SPC [key] [action] - Select window specified by [key] and
perform [action] on it, where [action] is an action keybinding.
For example, SPC a RET will switch to the desktop window
designated by 'a', whilst SPC c D will delete the desktop
window designated by 'c'.
```

Could you please check that it works for you?

**Comment by tumashu** [comment] 2015-05-10 00:24
good job, but not as expect, i use a  C-t w to pop a emacs frame to show ewmctrl,  i want to use a char to select  window  then kill this frame....

**Comment by flexibeast** [comment] 2015-05-10 02:25
i'm sorry, i don't follow. Do you want the `ewmctrl` frame to be deleted as soon as you've selected another window?

**Comment by tumashu** [comment] 2015-05-10 03:42
Right, I just use ewmctrl as a menu to quick select window, so when select finish, I kill ewmctrl frame, when I need, I just regenerate new ewmctrl frame.

**Comment by tumashu** [comment] 2015-05-10 03:44
I use emacs deamon mode , so create and delete frame quickly, if I were use  "[SPC] key cmd", I need 
type 5 char to switch window...

**Comment by tumashu** [comment] 2015-05-10 03:46
so, one char keybinding is my need....   for switch window is my frequent operate.

**Comment by flexibeast** [comment] 2015-05-10 04:35
Okay, that makes sense - thanks for explaining your use-case.

i also run Emacs in daemon mode, but don't create transient frames for things like `ewmctrl` as you do, so if switching windows automatically closed the frame containing `ewmctrl`, my main working frame would get closed. :-) Thus, my thought is to create a user-customisable option to enable/disable such functionality.

The one-key-to-switch-windows functionality is trickier. The problem is that several lower-case letters are already reserved for certain functionality - 'g' to refresh the window list, 'r' to resize a window, 'n' to move to the next line in the window list, 'p' to move to the previous line in the window list (the latter two being added in response to issue #5). And it's likely that more such letters will be assigned to other functionality in the future.

Thus, my thought is to create another user-customisable option which, when enabled, a single key means "switch to the window designated by that key", and (say) the key ';' will put the UI into the mode where 'g' refreshes the window list, 'r' resizes a window, etc.

Adding these two user-customisable options would allow users such as yourself to enable them to get the workflow you're after, whilst still allowing users with different workflows to leave one or both of them disabled (which would also preserve backwards-compatibility with the existing UI). 

Does that sound workable for you?

**Comment by tumashu** [comment] 2015-05-10 04:45
Thanks !

```
Thus, my thought is to create another user-customisable option which, when enabled, a single key means "switch to the window designated by that key", and (say) the key ';' will put the UI into the mode where 'g' refreshes the window list, 'r' resizes a window, etc.
```

This seem a good idea, if possible, add another custom , by which I can custom the window switch function

**Comment by flexibeast** [comment] 2015-05-10 04:57
> if possible, add another custom , by which I can custom the window switch function 

i'm sorry, i'm not sure i follow; could you elaborate, please?

**Comment by tumashu** [comment] 2015-05-10 05:07
sorry for my poor English,  when I switch to a window by type "a" for example,  it must call 
an window switch command, may be this command use some arguments.  is it possible custom this function?

**Comment by tumashu** [comment] 2015-05-10 05:15
for example:   

```
(defcustom ewmctrl-focus-window-function 'ewmctrl-focus-window)
```

**Comment by flexibeast** [comment] 2015-05-10 05:18
> sorry for my poor English

No need to apologise! i just want to make sure i properly understand what you're asking for, rather than assuming. :-)

> may be this command use some arguments. is it possible custom this function?

Well, at the moment, the function that does the actual switching is this:

``` elisp
(defun ewmctrl--focus-window-by-id (id)
  "Internal function to focus the desktop window specified
by ID."
  (call-process-shell-command (concat ewmctrl-wmctrl-path " -i -a '" id "'")))
```

Can you give me an example of how you might like to customise this?

**Comment by tumashu** [comment] 2015-05-10 08:07
Very simply: i need to delete current frame when ewmctrl in its own frame while don't delete current frame when ewmctrl in my main frame.  this just a suggest for this function is very simple and i can rewrite it easily....

for example:

```
(defun ewmctrl--focus-window-by-id (id)
   (call-process-shell-command (concat ewmctrl-wmctrl-path " -i -a '" id "'"))
 (when XXXXXX
   (delete-frame))
)
```

**Comment by flexibeast** [comment] 2015-05-10 08:24
Okay. Well, i've already added in the delete-frame functionality. :-)

More generally, if you want to do something before and/or after an arbitrary Emacs Lisp function, you can [advise that function](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html#Advising-Functions). At this point i'd rather not add numerous variables that can modify the behaviour of various `ewmctrl` actions, as that will complicate debugging in a way that i'm not sure is outweighed by potential benefits - particularly given that users can simply advise functions instead. However, i'm open to changing my mind if people can show me several compelling use-cases ....

**Comment by tumashu** [comment] 2015-05-10 08:32
Thanks!

```
At this point i'd rather not add numerous variables that can modify the behaviour of various ewmctrl actions
```

I agree!  Stable and consistent are very importent.

**Comment by tumashu** [comment] 2015-05-10 08:33
```
However, i'm open to changing my mind if people can show me several compelling use-cases ....
```

:-)

**Comment by tumashu** [comment] 2015-05-10 08:45
I think `ewmctrl-close-frame-on-focus-window' have problem:  when I set this variable to 't', 
If I occasionally use ewmctrl in my main emacs frame, my frame disapper  :-)

**Comment by tumashu** [comment] 2015-05-10 08:53
Maybe change  'ewmctrl-close-frame-on-focus-window' to  'ewmctrl-focus-window-post-hook'  is a good idea.

**Comment by flexibeast** [comment] 2015-05-10 09:06
> Maybe change 'ewmctrl-close-frame-on-focus-window' to 'ewmctrl-focus-window-post-hook' is a good idea.

No, because it's not a hook. A hook is something to which one can attach arbitrary code; `ewmctrl-close-frame-on-focus-window` is simply a boolean variable that can be either enabled or disabled.

**Comment by flexibeast** [comment] 2015-05-10 09:12
> I think `ewmctrl-close-frame-on-focus-window' have problem: when I set this variable to 't',
> If I occasionally use ewmctrl in my main emacs frame, my frame disapper :-)

Yep, exactly; it assumes you'll always use a new frame for an *ewmctrl* buffer, as that was the use-case you described.

i could add code to optionally not close a frame if it's the only extant frame. (Optional because i can imagine some users might want the frame closed even if it _is_ the last frame, e.g. if they're working in a terminal and only ever use `emacsclient` transiently.) Other than that, however, i'm not sure how the code can know which frame the user actually wants closed.

**Comment by tumashu** [comment] 2015-05-10 09:37
```
i could add code to optionally not close a frame if it's the only extant frame. (Optional because i can imagine some users might want the frame closed even if it is the last frame, e.g. if they're working in a terminal and only ever use emacsclient transiently.) Other than that, however, i'm not sure how the code can know which frame the user actually wants closed. 
```

I suggest this joy should do by user.   user can test Window-Class, Windon-title or other variable.  all ewmctrl need do is add a post hook variable and add a example

**Comment by flexibeast** [comment] 2015-05-10 09:47
Hmm. Can you please show how you'd use e.g. the window (by which i presume you mean desktop window, not Emacs window) class or window title to choose whether or not to close the frame?

**Comment by tumashu** [comment] 2015-05-10 09:51
NO, I mean is emacs-window, for example: if current emacs window instance match "WMCTRL",  delete window this frame after switch.

**Comment by flexibeast** [comment] 2015-05-10 09:57
No, that won't necessarily work. What if one has an *ewmctrl* buffer displayed in a window in the main frame, then pops a new frame to show the *ewmctrl* buffer? How can we determine, via Emacs Lisp, which frame contains the window to the *ewmctrl* buffer we want to close?

i'd like to suggest that you implement your desired functionality as advice on the existing `ewmctrl--focus-window` function; once you've got it reliably working as you want, i'll happily consider adding it to `ewmctrl.el`. :-)

**Comment by tumashu** [comment] 2015-05-10 10:27
```
i'd like to suggest that you implement your desired functionality as advice on the existing ewmctrl--focus-window function; once you've got it reliably working as you want, i'll happily consider adding it to ewmctrl.el. :-),  
```

general solution for delete frame is complex, so i don't suggest delete frame frame include ewmctrl, for
my personal use case, I create a new frame then open ewmctrl in this frame, so I can simple delete it. 

```
(defun shf/show-buffer-with-frame (name buffer)
  (let ((after-make-frame-functions
         #'(lambda (frame)
             (with-selected-frame frame
               (cfs-set-font-with-saved-step))
             (select-frame frame)
             (switch-to-buffer buffer))))
    (make-frame `((name . ,name)
                  (unsplittable . t)
                  (window-system . x)
                  (vertical-scroll-bars . nil)
                  (tool-bar-lines . 0)
                  (menu-bar-lines . 0)))))

(defun sfh/ewmctrl (&optional window-name)
  (interactive)
  (let ((buf (get-buffer-create "*ewmctrl*")))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (ewmctrl-refresh)
        (ewmctrl-mode)
        (goto-char (point-min))
        (forward-line 2)
        (setq mode-line-format nil)
        (visual-line-mode -1)
        (setq truncate-lines t)
        (define-key ewmctrl-mode-map (kbd "RET")
          #'(lambda ()
              (interactive)
              (ewmctrl-focus-window)
              (delete-frame)))))
    (shf/show-buffer-with-frame
     (or window-name "EWMCTRL-sfh/ewmctrl") buf)))

```

**Comment by tumashu** [comment] 2015-05-10 10:29
So all i need do is find an elisp function, which can return frame-class of current frame

**Comment by flexibeast** [comment] 2015-05-11 07:36
The single-key-to-focus functionality is now implemented. Can you please try it out to check if it works for you?

**Comment by flexibeast** [comment] 2015-05-11 07:40
> So all i need do is find an elisp function, which can return frame-class of current frame

Sorry, but i'm not familiar with frame classes in Emacs; could you point me to the relevant documentation? The phrase "frame class" doesn't appear in the index of the Emacs Lisp Reference Manual ....

**Comment by tumashu** [comment] 2015-05-11 09:47
'ewmctrl-single-key-to-focus-window ' can't enable the feature

**Comment by tumashu** [comment] 2015-05-11 09:52
```
(cdr (assoc 'name (frame-parameters)))
(insert (format "%S" (frame-parameters)))

```

**Comment by flexibeast** [comment] 2015-05-11 09:58
> 'ewmctrl-single-key-to-focus-window ' can't enable the feature

How are you trying to use that variable?

**Comment by tumashu** [comment] 2015-05-11 10:05
I try, but doesn't work, then i search this variable in ewmctrl code, seemd not find in function body

**Comment by flexibeast** [comment] 2015-05-11 10:17
Gah. That customisable variable shouldn't end in '-window'; that's an artifact from my initial implementation. Sorry! i've just pushed the fix.

**Comment by tumashu** [comment] 2015-05-11 10:22
I suggest this format:

```
Desktop   PID  [Key] Name
-------  ----- -----------
0        1837  [d] auto keybinding for switch window · Issue #8 · flexibeast/ewmctrl - Iceweasel
0        2464  [f] EMACSLOVE-sfh/emacs

```

**Comment by flexibeast** [comment] 2015-05-11 10:30
> I suggest this format

That format is certainly nice, but i think that the format in general is something that different users are going to have different opinions on. Something i'd like to do is make the order of the displayed fields user-customisable - i've just opened issue #9 for this. Controlling the format of the field headers and values is also something i want to do - i've just opened issue #10 for this. So once i've added these features, you'll be able to arrange the layout as you want. :-)

**Comment by tumashu** [comment] 2015-05-11 10:33
good idea!

**Comment by flexibeast** [comment] 2015-05-11 10:38
Re. "frame class" - ah, i understand what you mean now, thanks.

To return to a suggestion of yours, i'm thinking of adding a `ewmctrl-post-action-hook` variable, which would support what you want to do, without starting a cascade of additional hooks. What do you think?

**Comment by tumashu** [comment] 2015-05-11 11:21
Which function will  run  this  hook:  “ewmctrl-post-action-hook”

**Comment by flexibeast** [comment] 2015-05-11 11:33
It would be run at the end of `ewmctrl--dispatch-action`, and it would pass the character with which `ewmctrl--dispatch-action` was called to each of the functions in the hook; that way each function in the hook could decide whether to do something or not, based on the character received.

So what you could do is write a function that checks whether `overriding-local-map` is set to `ewmctrl-single-key-to-focus-map`, and then do various things after a desktop window has e.g. received the focus, or been deleted.

**Comment by tumashu** [comment] 2015-05-11 12:12
suggest:

```
(define-key ewmctrl-single-key-to-focus-map (kbd "RET") 'ewmctrl-focus-window)
```

**Comment by tumashu** [comment] 2015-05-11 12:19
```
It would be run at the end of ewmctrl--dispatch-action, and it would pass the character with which ewmctrl--dispatch-action was called to each of the functions in the hook;
```

I think if "ewmctrl-single-key-to-focus-map" use "ewmctrl--dispatch-action", add this post hook more useful.

**Comment by tumashu** [comment] 2015-05-11 12:21
```
It would be run at the end of ewmctrl--dispatch-action, and it would pass the character with which ewmctrl--dispatch-action was called to each of the functions in the hook;
```
I think if "ewmctrl-single-key-to-focus-map" use "ewmctrl--dispatch-action", add this post hook more useful.

**Comment by flexibeast** [comment] 2015-05-11 12:28
Re. the hook - yes, obviously i'd need to make changes elsewhere in the code. :-) i'm asking what you think of the overall idea, in principle?

i'm not sure i understand why you're suggesting adding RET to the `ewmctrl-single-key-to-focus-map`, since the point of single-key-to-focus is that one just types the window's key to focus that window, rather than moving point .... ?

**Comment by tumashu** [comment] 2015-05-11 13:18
"RET" is a single key and used to focus window.....

**Comment by tumashu** [comment] 2015-05-11 13:20
hook is a good idea, i think!

**Comment by flexibeast** [comment] 2015-05-11 13:45
> "RET" is a single key and used to focus window.....

Yes, but it would then usually require several other keypresses to move point to the window you want to focus, before you can then press RET to focus that window. And having to do so goes against the whole point of single-key-to-focus, which is to _not_ have to move point to select the window you want to focus.

Consequently, i'm going leave RET out of `ewmctrl-single-key-to-focus-map` for now.

So, to come back to the subject of this GitHub issue, is single-key-to-focus working for you (setting aside the RET keybinding)? If so, i'll close this issue.

i've also just pushed support for the `ewmctrl-post-action-hook` variable - let me know if it works for you. :-)

**Comment by tumashu** [comment] 2015-05-11 15:53
good job, this issue toooo long, should be closed...

**Comment by tumashu** [comment] 2015-05-12 05:37
run error:

```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101

```

**Comment by tumashu** [comment] 2015-05-12 05:49
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101

```

**Comment by tumashu** [comment] 2015-05-12 05:53
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101

```

**Comment by tumashu** [comment] 2015-05-12 05:54
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101
```

**Comment by tumashu** [comment] 2015-05-12 05:54
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101
```

**Comment by tumashu** [comment] 2015-05-12 05:55
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101
```

**Comment by tumashu** [comment] 2015-05-12 05:56
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101
```

**Comment by tumashu** [comment] 2015-05-12 05:59
run error:
```
Single key now focuses window.
user-error: ewmctrl--dispatch-action: don't know how to handle character 101
```

**Comment by tumashu** [comment] 2015-05-12 07:31
don't work:

```
(defun sfh/ewmctrl-post-action (char key)
  (delete-frame)
  ;; (let ((frame-name (cdr (assoc 'name (frame-parameters)))))
  ;;   (if (string-match "^EWMCTRL" frame-name)
  ;;       (delete-frame)))
  )

(add-hook 'ewmctrl-post-action-hook 'sfh/ewmctrl-post-action)

```

**Comment by flexibeast** [comment] 2015-05-12 08:22
> user-error: ewmctrl--dispatch-action: don't know how to handle character 101

Sorry, but i can't reproduce this error here. Could you please describe the exact steps you took, including all keys you pressed?

**Comment by flexibeast** [comment] 2015-05-12 08:31
> don't work

However, i can reproduce this - sorry. i'll try to fix this asap.

**Comment by flexibeast** [comment] 2015-05-12 09:05
i've just pushed some changes involving `ewmctrl-post-action-hook`. In particular, please note that the arguments with which functions in `ewmctrl-post-action-hook` are called are now reversed, i.e. the arguments are now KEY CHAR.

Could you please check if this hook now works for you? Thank you for your time and patience with this!

**Comment by tumashu** [comment] 2015-05-12 10:21
ewmctrl-post-action-hook can works,  i think another problem:  ewmctrl function should include the below code....

```
(when ewmctrl-single-key-to-focus
  (setq-local overriding-local-map ewmctrl-single-key-to-focus-map))
```

**Comment by flexibeast** [comment] 2015-05-12 10:25
Glad the hook now works. :-)

The `setq-local` to which you refer is already done in the `ewmctrl-toggle-single-key-to-focus` function; see lines 754 and 757 [here](https://github.com/flexibeast/ewmctrl/blob/master/ewmctrl.el).

**Comment by tumashu** [comment] 2015-05-12 10:31
```
The setq-local to which you refer is already done in the ewmctrl-toggle-single-key-to-focus function; see lines 754 and 757 here.
```

I know this, but when i set ewmctrl-toggle-single-key-to-focus to t,  ewmctrl should enable this feature 
when start, toggle-function can't do this job...

**Comment by flexibeast** [comment] 2015-05-12 10:31
Oh! i think i see what you mean: if `ewmctrl-single-key-to-focus` is already set when `ewmctrl` is first called, then `ewmctrl-toggle-single-key-to-focus` doesn't get called, and so `overriding-local-map` doesn't get set as it should.

**Comment by tumashu** [comment] 2015-05-12 10:32
yes!

**Comment by flexibeast** [comment] 2015-05-12 10:35
Okay, fix pushed!

**Comment by flexibeast** [comment] 2015-05-13 01:28
i believe this issue can now be closed. @tumashu, do you agree?

**Comment by tumashu** [comment] 2015-05-13 03:39
ok

**Comment by flexibeast** [comment] 2015-05-13 03:52
Will do. Thanks for all your assistance - very much appreciated!

**Closed as completed by flexibeast** 2015-05-13 03:52 UTC
Labels: enhancement

**Comment by flexibeast** [comment] 2015-06-30 10:22
@tumashu:

i've just added functionality for users to change the layout of the window list, via `ewmctrl-format-header`, `ewmctrl-format-fields` and `ewmctrl-format-fields-order`, to address issues #9 and #10. Would you like to try the new functionality, and confirm that it works for you?
